### ISSUE TITLE
Не сохраняет куки

### ISSUE THREAD

**Issue by uitlaber** [TsSaltan/DevelNext-jURL#8]
При запросе файл с куками создается а внутри пустой массив

**Comment by TsSaltan** [comment]
@uitlaber, нужен код, который вызывает эту ошибку

**Comment by uitlaber** [comment]
$login = $this->login->text;
        $password = $this->password->text;
        $data = [            
            'login' => $login,
            'passwd' => $password,
        ];
        $url = 'http://site.ru/';
        $ch = curl_init($url);
         curl_setopt( $ch, CURLOPT_COOKIESESSION, true );
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_COOKIEJAR,  'cookies.json');
        curl_setopt($ch, CURLOPT_COOKIEFILE, 'cookies.json');      
        curl_setopt($ch, CURLOPT_HEADER, true);        
        $result =  curl_exec($ch);
        $this->textArea->text = $result;

**Comment by TsSaltan** [comment]
@uitlaber не удаётся повторить, какой url сайта? в каком формате отдаются куки?

**Comment by uitlaber** [comment]
@TsSaltan  https://freelance.ru/login/

**Comment by TsSaltan** [comment]
Не подтверждено, возможно, после исправленного бага #13 , всё будет работать
